### ISSUE TITLE
"Convert to Pure Component" won't parse tsx

### ISSUE THREAD

**Issue by paprikati** [nicoespeon/abracadabra#397] opened 2021-09-28 10:07 UTC
I'm getting errors when trying to use the extension like:
![image](https://user-images.githubusercontent.com/50166767/135067241-b3d3df8c-40cc-4283-ad69-26b6c5394f72.png)

in both cases, what's happening is the extension is trying to parse a `.tsx` file as javascript, and therefore erroring when it sees something that isn't valid jsx (like a type definition, or the keyword interface).

I'm assuming this is because it's not picking up the correct configuration to give to babel. is there a way I can explicitly pass in some babel configuration options so the extension can parse the code correctly? Or is there a specific place I need to put a babel config file?

Thanks!

**Comment by paprikati** [comment] 2021-09-28 10:49
For context, our bable config is:
```
{
  "presets": ["@babel/preset-react", "@babel/preset-env"],
  "plugins": ["@babel/plugin-transform-react-jsx"]
}
```

I can see in the source code that you specify a list of plugins (and no presets) - could we make those into configuration options which I could override from settings, perhaps?

**Comment by paprikati** [comment] 2021-09-28 10:52
however, I've just pulled a dev copy of the extension and overridden the presets and plugins, and I'm still getting the same error - which is curious. I'm going to try and pull together a demo repo that hopefully you can repro it with

**Comment by paprikati** [comment] 2021-09-28 11:15
I've pulled together an example repo [here](https://github.com/paprikati/vscode-refactor-test) - hopefully this will help with debugging?

**Comment by nicoespeon** [comment] 2021-09-29 01:22
Thanks for the details and the example repo @paprikati, I'll have a look at that.

It's curious indeed because the extension should definitely be able to parse TSX code. But there's probably something weird going on and I'll find it 🕵️

**Comment by nicoespeon** [comment] 2021-09-30 14:13
Hey @paprikati 👋 

I cloned the example repo and it seems that I can run refactorings just fine on the .tsx files:
![CleanShot 2021-09-30 at 08 28 27](https://user-images.githubusercontent.com/1094774/135455189-a3796b2c-d4d4-47c5-8740-d01d94d2df2b.gif)

So that might be something else. Can you confirm for me:
1. Which refactorings you're trying to execute on which file? So I could try the exact same operation
2. Which OS are you working on? 
3. Which version of VS Code do you have?

Thank you!

**Comment by paprikati** [comment] 2021-09-30 14:17
That's really weird. It's now working. I can't tell you what I'm doing differently. I must have been doing something dumb ...?
thanks for the quick turnaround, sorry for the red herring!

**Comment by paprikati** [comment] 2021-09-30 14:17
My end goal is to get a refactor that will extract a TSX component for me, and generate types. Gonna start having a play this week - will let you know if I get anywhere.

**Comment by paprikati** [comment] 2021-09-30 14:19
interestingly, I still get that error if I try to run the react 'extract a pure component' refactor on a class component like
```
class Welcome extends React.Component {
    render() {
        return <div>
        <div>
            String: <div>{this.props.str}</div>
        </div>
        <div>
            Number: <div>{this.props.num}</div>
        </div>
        <div>
            Boolean: <div>{this.props.bool}</div>
        </div>
    </div>    
    }
  }
```

**Comment by nicoespeon** [comment] 2021-09-30 14:21
That's weird but weird things happen sometimes 😆 

Glad it's working now. Let me know if I can help you with anything 👍 
I'll let you close the issue, unless you had another question?

**Comment by paprikati** [comment] 2021-09-30 14:22
sorry, could you check out the pure component refactor issue? I think maybe we had a race condition on github posts just then!

**Comment by nicoespeon** [comment] 2021-09-30 14:25
Oh yeah! There is def. something going on with `Convert to Pure Component`. I'll have a look at this one 👍 m

**Comment by paprikati** [comment] 2021-09-30 16:57
I think that maybe it's all typescript that's the problem? But most of the refactorings don't look at the type annotations as they aren't looking at the function declaration itself, so they don't notice the difference?

**Comment by nicoespeon** [comment] 2021-09-30 17:25
@paprikati I don't really think so. TS code can be parsed fine and we have TS-specific refactorings such as "Extract Type".

"Convert to Pure Component" is a refactoring we actually delegate to `react-codemod/transforms/pure-component` here: https://github.com/nicoespeon/abracadabra/blob/main/src/refactorings/react/convert-to-pure-component/convert-to-pure-component.ts

I suspect the issue may come from that lib. Maybe it started to break once we upgraded last month: https://github.com/nicoespeon/abracadabra/commit/0adb87d4c5f8f05e6065aed07dc7ab8fa378ec21

I'd start by writing a test that involves TS code for this refactoring, see if we have the same issue (we should). If so, see if upgrading or downgrading fixes it. If not, try to understand what's going on exactly and see if there's something we can do 🤔

**Comment by paprikati** [comment] 2021-09-30 21:53
Makes sense! - I'll try the things you suggest tomorrow if I get time, but I'm likely to need some help getting to the bottom of this I suspect. I'll update if I get anywhere

**Comment by nicoespeon** [comment] 2021-10-01 00:13
Thank you! I planned to get to this on Sunday (I'll have some free time) if you couldn't solve it, so no worry 😉

**Comment by nicoespeon** [comment] 2021-10-03 12:13
The root cause seems to come from jscodeshift. `react-codemod` is delegating the work to the jscodeshift instance we are passing: 

https://github.com/reactjs/react-codemod/blob/b34b92a1f0b8ad333efe5effb50d17d46d66588b/transforms/pure-component.js#L11-L12

In Abracadabra, we inject the instance from the latest available version (v0.13.0 as for now):
https://github.com/nicoespeon/abracadabra/blob/8e56f6e97a4fa1d69e57e7a72f9f8a0be508451d/src/refactorings/react/convert-to-pure-component/convert-to-pure-component.ts#L52

But this version seems to have issues parsing the `.tsx` we have. For instance, people have trouble running it when there are interfaces: https://github.com/facebook/jscodeshift/issues/421

The main solution to this would be for jscodeshift to fix the issues. We could help them by adding more details/repro examples to illustrate the issues. If they fix it, we'll simply upgrade and that will work.

Until then, "Convert to Pure Component" essentially works with JS files.

Another option would be to implement this refactoring ourselves, but it's not a priority for me (I'm focused on making Abracadabra works with multiple files = you can refactor something that's exported).

**Comment by nftnoob** [comment] 2021-12-06 13:53
any updated on this?

**Comment by nicoespeon** [comment] 2021-12-06 15:37
@nftnoob no news nope. It depends on https://github.com/facebook/jscodeshift/issues/421 resolution and it doesn't seem to have changed since.

**Comment by nicoespeon** [comment] 2023-04-14 02:10
Not relevant anymore, we dropped this refactoring. Read https://github.com/nicoespeon/abracadabra/blob/main/docs/adr/0013-remove-extract-class-and-convert-to-pure-component-refactorings.md to learn more.

**Closed by nicoespeon** 2023-04-14 02:10 UTC
Labels: :bug: Bug, 🙅 Blocked by 3rd party
