### ISSUE TITLE
abracadabra renameSymbol not found

### ISSUE THREAD

**Issue by nmay231** [nicoespeon/abracadabra#1055] opened 2024-08-09 03:43 UTC
## Describe the bug

Something changed when vscode updated for me just now that breaks renaming things in a typescript project with `F2`.

## How to reproduce

In version vscode 1.92.1, try to rename a symbol (variable or type/interface) in typescript. Nothing happens except a warning/error notification in the bottom right.

## Expected behavior

I expected the default renaming dialog to pop up, but perhaps Abracadabra is hooking into this feature when it's not supposed to? Or it's not failing gracefully like it should.

## Screenshots

![image](https://github.com/user-attachments/assets/06b631dc-531b-4a49-b012-d797a14b8915)

## Additional information

- Version of the extension impacted: _v9.4.0_

I just deleted the keyboard shortcut that abracadabra hooks into to get on with life for now, but I'm sure that's just a quick workaround. Let me know if this is not reproducible on your end and I'll try with a clean profile to narrow down the problem.

**Comment by GollyJer** [comment] 2024-08-09 04:20
Came to support the same thing.

**Comment by nicoespeon** [comment] 2024-08-09 11:32
Thanks for reporting, I can confirm the same thing is happening for all refactorings. I'm debugging this. Seems to be related to v9.4.0. The weird part is that this issue doesn't show up when debugging the extension locally, but once published it is not working.

I'll get a resolution asap.

**Comment by nicoespeon** [comment] 2024-08-09 12:14
@GollyJer @nmay231 v9.4.1 seems to have fixed it for me. Could you try to upgrade and let me know if it works for you too?

It seems that the issue was with the upgrade of esbuild from 0.19 to 0.22 (https://github.com/nicoespeon/abracadabra/pull/1032). I should have been more careful about this because it only manifests when you package the extension.

Hopefully, it seems that they reverted the problematic changes with 0.23: https://github.com/evanw/esbuild/blob/main/CHANGELOG.md#0230

But I'm waiting for other people to confirm the fix is working before closing this issue.

**Comment by GollyJer** [comment] 2024-08-09 16:53
Working for me. Thanks!

**Comment by nicoespeon** [comment] 2024-08-09 17:03
Got 2 confirmations + me, so I think this is fixed. Yay!

**Closed by nicoespeon** 2024-08-09 17:03 UTC
Labels: :bug: Bug

**Comment by nmay231** [comment] 2024-08-09 19:03
Thanks for the quick fix!
