### ISSUE TITLE
Move to existing file: won't suggest "modules" folder

### ISSUE THREAD

**Issue by b-pmcg** [nicoespeon/abracadabra#484] opened 2022-01-12 02:16 UTC
I'm trying to use the Move to Existing File feature, and I can see most of the code as an option, but no files inside my "modules" folder are detected. My project does not have a "src" folder in the root, the file structure looks something like this:

```
-lib
-modules
-pages
...
```

"lib" and "pages" are both detected and suggested.

**Comment by nicoespeon** [comment] 2022-01-13 01:06
Oh, that's interesting. I will check on my end and see if I can repro. I have a suspicion this could be due to a bad matching since I know we are omitting "node_modules" by default 🤔

**Comment by nicoespeon** [comment] 2022-01-13 01:21
OK, that's weird because it looks like I'm able to move things to a `modules` folder, like so: 
![CleanShot 2022-01-12 at 20 19 18](https://user-images.githubusercontent.com/1094774/149248742-485a49c8-140a-4ce6-9642-9552b93f7150.png)

Could you check your settings and verify if there is any value for `abracadabra.ignoredFolders`? If not, the default will be:

```json
  "abracadabra.ignoredFolders": [
    "node_modules",
    "dist",
    "build"
  ],
```

Now, if I add `"modules"` to this list, then these files disappear indeed (which is the expected behavior).

**Comment by b-pmcg** [comment] 2022-01-14 23:22
Hey, sorry for the late response. After digging around a bit I realized it is finding folders in `modules` directory, but its not finding typescript definition files, so files ending in `*.d.ts` (which all happen to be in my modules dir :) )

**Comment by nicoespeon** [comment] 2022-01-16 13:25
Ah yes! Indeed, it explicitly excludes `.d.ts` files because they don't behave like regular `.ts` files: https://github.com/nicoespeon/abracadabra/blob/1a78ef8279c42ff45c63f72ada8dc47e0f29640e/src/editor/adapters/vscode-editor.ts#L35 

That's because you can't move any kind of code there.

Does this solve your question? Or is "moving to .d.ts files" a feature you'd need?

**Comment by b-pmcg** [comment] 2022-01-17 00:53
ah, gotcha, thanks for the explanation. It would nice to be able to re-organize types a bit, but I wouldn't say it is essential for me :)

**Comment by nicoespeon** [comment] 2022-01-17 13:36
@b-pmcg got it! I'm closing this issue then. I will keep the idea on the backburner and see if there is more demand for it.

**Closed by nicoespeon** 2022-01-17 13:36 UTC
Labels: :question: Question
