### ISSUE TITLE
Not all options are showed in "Quick Fix" menu

### ISSUE THREAD

**Issue by MintMissy** [nicoespeon/abracadabra#792] opened 2023-01-12 00:46 UTC
## Describe the bug

The quick fix menu doesn't show all available refactoring options. (typescript)

## How to reproduce

To see all available options you must open the **Quick Fixes Menu** from the error hover widget (it works as expected).

Although when I try opening the **Quick Fix Menu** by using the shortcut `Alt + Enter`, (I believe it's `ctrl + .` by default) the quick fix menu looks a little bit different and misses 2 extra options - **Add missing properties** and **Remove unused declaration**.

## Expected behavior

Show all available refactoring options in the menu opened by using a shortcut.

## Screenshots

- The hover widget. It opens refactor menu with all properties after clicking in **Quick Fix... (Alt + Enter)**
![Hover](https://i.postimg.cc/tTK5VKp5/quickfix3.png)

- Menu with all properties opened by using a quick-fix link
![Menu with all properties](https://i.postimg.cc/gJXsjzFj/quickfix2.png)

- Menu with missing properties
![Menu with missing properties](https://i.postimg.cc/g0B4Gw71/quickfix1.png)

## Additional information

- Version of the extension impacted: _v6.18.2_
- I've tried changing the shortcut to the default one - it works exactly in the same way.

**Comment by nicoespeon** [comment] 2023-01-12 14:07
Hi there @MintMissy 👋 

Thank you for the very detailed report with the screenshots, that was really helpful to understand what's going on.

The problem isn't coming from Abracadabra. In fact, Abracadabra's quick fixes are the ones with a ✨  suffix (Move to an existing file, Inline variable, Split declaration and initialization). They don't appear when you click the "Quick Fix" link it seems… and I _think_ I know why.

In fact, the Quick Fix you are mentioning are provided by TypeScript itself. They are implemented in https://github.com/microsoft/TypeScript (for instance, [Add missing properties](https://github.com/microsoft/TypeScript/blob/67cdaf921518a0b4dd9b05e026b2f65ba0edcef2/src/compiler/diagnosticMessages.json#L7431)).

My guess is that when you click the link from the TS popup, it only shows you TS quick fixes. Now, I don't know why some of these are missing when you click on the lightbulb or trigger the Quick Fixes with the shortcut instead 🤔 

In any case, you should open this issue in this repository instead: https://github.com/microsoft/TypeScript
I'm sorry I can't help you more 😅  Hopefully, they will be able to explain _why_ and maybe make it more consistent.

I'm closing this issue but feel free to comment if you think I've missed something!

**Closed by nicoespeon** 2023-01-12 14:07 UTC
Labels: :bug: Bug
